. env/chpl-env-snellius.sh
export LD_LIBRARY_PATH="$PWD/third_party/lib:$LD_LIBRARY_PATH"
source "${CHPL_HOME}/util/setchplenv.bash"
# export CHPL_RT_OVERSUBSCRIBED=yes
# export OMP_NUM_THREADS=1
export GASNET_PHYSMEM_MAX='167 GB'
export HDF5_USE_FILE_LOCKING=FALSE

# Allocating resources:
# srun -N 2 --exclusive -t 30:00 -W 0 --pty /bin/bash -il
example05() {
    case "$1" in
        -nl)
            NUM_LOCALES=$2
            shift
            shift
            ;;
        -nl*)
            NUM_LOCALES="${1#-nl}"
            shift
            ;;
        *)
            echo "Expected -nl argument specifying the number of locales"
            return 1
    esac
    $CHPL_HOME/third-party/gasnet/install/linux64-x86_64-unknown-llvm-none/substrate-ibv/seg-large/bin/gasnetrun_ibv \
        -n $NUM_LOCALES -N $NUM_LOCALES -c 0 \
        -E LD_LIBRARY_PATH,SSH_CONNECTION,CHPL_RE2,CHPL_LAUNCHER,CHPL_GMP,CHPL_COMM_SUBSTRATE,PWD,HOME,SSH_CLIENT,CHPL_COMM,CHPL_HWLOC,CHPL_UNWIND,CHPL_LLVM,CHPL_HOME,PATH,SLURM_JOB_ID,GASNET_PHYSMEM_MAX,HDF5_USE_FILE_LOCKING,SLURM_CONF,SLURM_ECPLUG,SLURM_ECLIBR,SURF_EXCLUSIVE,SLURM_MPI_TYPE,SLURM_ERLAST,SLURM_ERSRUN,SLURM_PRIO_PROCESS,SRUN_DEBUG,SLURM_UMASK,SLURM_CLUSTER_NAME,SLURM_SUBMIT_DIR,SLURM_SUBMIT_HOST,SLURM_JOB_CPUS_PER_NODE_PACK_GROUP_0,SLURM_NTASKS,SLURM_NPROCS,SLURM_DISTRIBUTION,SLURM_JOBID,SLURM_JOB_NAME,SLURM_STEP_ID,SLURM_STEPID,SLURM_NODELIST,SLURM_JOB_PARTITION,SLURM_TASKS_PER_NODE,SLURM_SRUN_COMM_PORT,SLURM_JOB_UID,SLURM_JOB_USER,SLURM_WORKING_CLUSTER,SLURM_SCRIPT_CONTEXT,SLURM_JOB_NODELIST,SLURM_STEP_NODELIST,SLURM_STEP_NUM_NODES,SLURM_STEP_NUM_TASKS,SLURM_STEP_TASKS_PER_NODE,SLURM_STEP_LAUNCHER_PORT,SLURM_STEP_RESV_PORTS,SLURM_NNODES,SLURM_SRUN_COMM_HOST,SLURM_TOPOLOGY_ADDR,SLURM_TOPOLOGY_ADDR_PATTERN,EAR_TMP,EAR_INSTALL_PATH,SLURM_CPUS_ON_NODE,SLURM_CPU_BIND,SLURM_CPU_BIND_LIST,SLURM_CPU_BIND_TYPE,SLURM_CPU_BIND_VERBOSE,SLURM_TASK_PID,SLURM_NODEID,SLURM_PROCID,SLURM_LOCALID,SLURM_LAUNCH_NODE_IPADDR,SLURM_GTIDS,SLURM_JOB_GID,SLURMD_NODENAME,PMI_FD,PMI_JOBID,PMI_RANK,PMI_SIZE,TMPDIR \
        env LANG=en_US.UTF-8 LC_ALL= LC_COLLATE= \
        $PWD/bin/Example05_real -nl $NUM_LOCALES -v
}
