name: CI

on: [push, pull_request]

env:
  LS_HS_VERSION: "0754e43"

defaults:
  run:
    shell: bash

jobs:
  linux_tests:
    runs-on: ubuntu-latest
    container:
      image: chapel/chapel:1.29.0 # or chapel/chapel-gasnet-smp if you want multi-locale
    steps:
    - uses: actions/checkout@v2
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y --no-install-recommends \
          patchelf bzip2 unzip \
          libnuma-dev libgmp-dev libffi-dev \
          libhdf5-dev libhdf5-hl-100

    - name: Install lattice-symmetries-haskell
      run: |
        wget --no-verbose https://github.com/twesterhout/lattice-symmetries-haskell/releases/download/continuous/lattice-symmetries-haskell-${LS_HS_VERSION}-ubuntu-18.04.tar.bz2
        tar -xf lattice-symmetries-haskell-${LS_HS_VERSION}-ubuntu-18.04.tar.bz2
        mv lattice-symmetries-haskell-${LS_HS_VERSION} third_party
        # patchelf --set-rpath '$ORIGIN' third_party/lib/liblattice_symmetries_haskell.so
        # ldd third_party/lib/liblattice_symmetries_haskell.so

    - name: Build
      run: |
        # source env/setup-env-comm-none.sh
        export LD_LIBRARY_PATH="$PWD/third_party/lib:$LD_LIBRARY_PATH"
        make

    - uses: actions/cache@v3
      name: Cache test data
      with:
        path: |
          data/matvec
        key: test-data
    - name: Test
      run: |
        if [ ! -d "data/matvec" ]; then make data/matvec; fi
        make check

    - name: Examples
      run: |
        export LD_LIBRARY_PATH="$PWD/third_party/lib:$LD_LIBRARY_PATH"
        bin/Example02
        bin/Example05

    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        channels: conda-forge,defaults
        channel-priority: true
        auto-activate-base: false

    - name: Create Conda environment
      run: |
          mamba env create -f conda-ci-linux.yml

    - name: Build foreign library
      run: |
        make OPTIMIZATION=--fast lib
        make OPTIMIZATION=--fast release

        # - uses: actions/cache@v3
        #   name: Cache Chapel runtime
        #   with:
        #     path: |
        #       /opt/chapel
        #     key: chapel-runtime

        # - name: Build Chapel runtime
        #   run: |
        #     # echo "CHPL_HOME=${CHPL_HOME}"
        #     source env/setup-env-comm-none.sh
        #     $CHPL_HOME/util/chplenv/printchplbuilds.py
        #     pushd $CHPL_HOME
        #     make -j2
        #     popd

  mac_tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew install chapel hdf5

        wget -q https://github.com/twesterhout/lattice-symmetries-haskell/releases/download/continuous/lattice-symmetries-haskell-${LS_HS_VERSION}-macos-latest.tar.bz2
        tar -xf lattice-symmetries-haskell-${LS_HS_VERSION}-macos-latest.tar.bz2
        mv lattice-symmetries-haskell-${LS_HS_VERSION} third_party
        otool -L third_party/lib/liblattice_symmetries_haskell.dylib

    - name: Build
      run: |
        make

    - uses: actions/cache@v3
      name: Cache test data
      with:
        path: |
          data/matvec
        key: test-data
    - name: Test
      run: |
        if [ ! -d "data/matvec" ]; then make data/matvec; fi
        make check

    - name: Examples
      run: |
        export DYLD_LIBRARY_PATH=$PWD/third_party/lib:$DYLD_LIBRARY_PATH
        bin/Example02
        bin/Example05

    - name: Build foreign library
      run: |
        make OPTIMIZATION=--fast lib
        make OPTIMIZATION=--fast release
